services:
  
  hddfancontrol:
    privileged: true
    image: ghcr.io/tr1plus/docker-hddfancontrol2:main
    container_name: hddfancontrol
    environment:
     - DEVICES=${DEVICES}
     - PWM=${PWM}
