services:
  
  hddfancontrol:
    build:
      context: .
      dockerfile_inline: |
          FROM debian
          WORKDIR /hddfancontrol
          RUN apt update
          RUN apt install wget hdparm sdparm smartmontools lm-sensors fancontrol
          RUN wget https://github.com/desbma/hddfancontrol/releases/download/2.0.2/hddfancontrol_2.0.2-1_amd64.deb
          RUN dpkg -i hddfancontrol_2.0.2-1_amd64.deb
          RUN hddfancontrol daemon -d /dev/sda -p /sys/class/hwmon/hwmon6/pwm3:200:30 --min-fan-speed-prct 10 -i 1min